// <auto-generated />
using System;
using Amanaje_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Amanaje_API.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Amanaje_API.Models.Externals.ClienteExternal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CLIENTE");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("TB_AMANAJE_CLI", (string)null);
                });

            modelBuilder.Entity("Amanaje_API.Models.Externals.UsuarioExternal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("TB_AMANAJE_USU", (string)null);
                });

            modelBuilder.Entity("Amanaje_API.Models.ObservacaoClimatica", b =>
                {
                    b.Property<int>("IdObservacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_OBSERVACAO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdObservacao"));

                    b.Property<DateTime>("DtCriadoEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIADO_EM");

                    b.Property<DateTime>("DtObs")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_OBS");

                    b.Property<int>("IdRegiao")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_REGIAO");

                    b.Property<string>("NmFonte")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)")
                        .HasColumnName("NM_FONTE");

                    b.Property<decimal?>("NrIndiceUv")
                        .HasPrecision(5, 2)
                        .HasColumnType("DECIMAL(5,2)")
                        .HasColumnName("NR_INDICE_UV");

                    b.Property<decimal?>("NrPrecipMm")
                        .HasPrecision(8, 2)
                        .HasColumnType("DECIMAL(8,2)")
                        .HasColumnName("NR_PRECIP_MM");

                    b.Property<decimal?>("NrPressaoHpa")
                        .HasPrecision(8, 2)
                        .HasColumnType("DECIMAL(8,2)")
                        .HasColumnName("NR_PRESSAO_HPA");

                    b.Property<decimal?>("NrRadiacaoSolar")
                        .HasPrecision(10, 2)
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("NR_RADIACAO_SOLAR");

                    b.Property<decimal?>("NrTemperaturaC")
                        .HasPrecision(6, 2)
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("NR_TEMPERATURA_C");

                    b.Property<decimal?>("NrUmidadePct")
                        .HasPrecision(5, 2)
                        .HasColumnType("DECIMAL(5,2)")
                        .HasColumnName("NR_UMIDADE_PCT");

                    b.Property<decimal?>("NrVentoKmh")
                        .HasPrecision(8, 2)
                        .HasColumnType("DECIMAL(8,2)")
                        .HasColumnName("NR_VENTO_KMH");

                    b.HasKey("IdObservacao");

                    b.HasIndex("IdRegiao");

                    b.HasIndex("IdObservacao", "IdRegiao")
                        .IsUnique()
                        .HasDatabaseName("UQ_AMANAJE_OBS_ID_REGIAO");

                    b.ToTable("TB_AMANAJE_OBS_CLIM", t =>
                        {
                            t.HasCheckConstraint("CK_AMANAJE_OBS_PREC", "NR_PRECIP_MM IS NULL OR NR_PRECIP_MM >= 0");

                            t.HasCheckConstraint("CK_AMANAJE_OBS_PRESSAO", "NR_PRESSAO_HPA IS NULL OR NR_PRESSAO_HPA BETWEEN 800 AND 1200");

                            t.HasCheckConstraint("CK_AMANAJE_OBS_UMIDADE", "NR_UMIDADE_PCT IS NULL OR NR_UMIDADE_PCT BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_AMANAJE_OBS_UV", "NR_INDICE_UV IS NULL OR NR_INDICE_UV BETWEEN 0 AND 20");

                            t.HasCheckConstraint("CK_AMANAJE_OBS_VENTO", "NR_VENTO_KMH IS NULL OR NR_VENTO_KMH >= 0");
                        });
                });

            modelBuilder.Entity("Amanaje_API.Models.Processamento", b =>
                {
                    b.Property<int>("IdProcessamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PROCESSAMENTO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProcessamento"));

                    b.Property<string>("DsOrigem")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)")
                        .HasColumnName("DS_ORIGEM");

                    b.Property<string>("DsParam")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("DS_PARAM");

                    b.Property<string>("DsResult")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("DS_RESULT");

                    b.Property<DateTime?>("DtFim")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_FIM");

                    b.Property<DateTime>("DtInicio")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_INICIO");

                    b.Property<int?>("IdRegiao")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_REGIAO");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<string>("StProcess")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ST_PROCESS");

                    b.Property<string>("TpProcess")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TP_PROCESS");

                    b.HasKey("IdProcessamento");

                    b.HasIndex("IdRegiao");

                    b.HasIndex("IdUsuario");

                    b.ToTable("TB_AMANAJE_PROCESS", t =>
                        {
                            t.HasCheckConstraint("CK_AMANAJE_PROCESS_FIM", "DT_FIM IS NULL OR DT_FIM >= DT_INICIO");

                            t.HasCheckConstraint("CK_AMANAJE_PROCESS_STATUS", "ST_PROCESS IN ('INICIADO','EM_EXECUCAO','CONCLUIDO','FALHOU','CANCELADO')");

                            t.HasCheckConstraint("CK_AMANAJE_PROCESS_TIPO", "TP_PROCESS IN ('SINCRONIZACAO_CLIM','CALCULO_RISCO','GERACAO_IND','GERACAO_ALERTA','CARGA_DADOS','ROTINA_PL_SQL','OUTRO')");
                        });
                });

            modelBuilder.Entity("Amanaje_API.Models.RegiaoMonitorada", b =>
                {
                    b.Property<int>("IdRegiao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_REGIAO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRegiao"));

                    b.Property<string>("DsMotivoExclusao")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("DS_MOTIVO_EXCLUSAO");

                    b.Property<DateTime?>("DtAtualizadoEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ATUALIZADO_EM");

                    b.Property<DateTime>("DtCriadoEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIADO_EM");

                    b.Property<DateTime?>("DtDelEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_DEL_EM");

                    b.Property<int>("IdCliente")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CLIENTE");

                    b.Property<int?>("IdDelPor")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_DEL_POR");

                    b.Property<string>("NmCidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NM_CIDADE");

                    b.Property<string>("NmRegiao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NM_REGIAO");

                    b.Property<decimal>("NrLatitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("DECIMAL(9,6)")
                        .HasColumnName("NR_LATITUDE");

                    b.Property<decimal>("NrLongitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("DECIMAL(9,6)")
                        .HasColumnName("NR_LONGITUDE");

                    b.Property<int>("NrNivelVuln")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NR_NIVEL_VULN");

                    b.Property<string>("SgEstado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("NVARCHAR2(2)")
                        .HasColumnName("SG_ESTADO");

                    b.Property<string>("StAtivo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ST_ATIVO");

                    b.Property<string>("TpArea")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TP_AREA");

                    b.Property<string>("TpVisib")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TP_VISIB");

                    b.HasKey("IdRegiao");

                    b.HasIndex("IdDelPor");

                    b.HasIndex("IdCliente", "NmRegiao")
                        .IsUnique()
                        .HasDatabaseName("UQ_AMANAJE_REGIAO_CLI_NOME");

                    b.ToTable("TB_AMANAJE_REGIAO_MONIT", t =>
                        {
                            t.HasCheckConstraint("CK_AMANAJE_REGIAO_AREA", "TP_AREA IN ('PONTE','ENCOSTA','AREA_RURAL','COMUNIDADE','PROPRIEDADE_PRIVADA','REGIAO_RIBEIRINHA','AREA_URBANA','OUTRA')");

                            t.HasCheckConstraint("CK_AMANAJE_REGIAO_ATIVO", "ST_ATIVO IN ('S','N')");

                            t.HasCheckConstraint("CK_AMANAJE_REGIAO_DEL", "(ST_ATIVO = 'S' AND DT_DEL_EM IS NULL) OR (ST_ATIVO = 'N')");

                            t.HasCheckConstraint("CK_AMANAJE_REGIAO_ESTADO", "REGEXP_LIKE(SG_ESTADO, '^[A-Z]{2}$')");

                            t.HasCheckConstraint("CK_AMANAJE_REGIAO_LAT", "NR_LATITUDE BETWEEN -90 AND 90");

                            t.HasCheckConstraint("CK_AMANAJE_REGIAO_LONG", "NR_LONGITUDE BETWEEN -180 AND 180");

                            t.HasCheckConstraint("CK_AMANAJE_REGIAO_VISIB", "TP_VISIB IN ('PRIVADA','INSTITUCIONAL','AGREGADA_PUBLICA')");

                            t.HasCheckConstraint("CK_AMANAJE_REGIAO_VULN", "NR_NIVEL_VULN BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("Amanaje_API.Models.ObservacaoClimatica", b =>
                {
                    b.HasOne("Amanaje_API.Models.RegiaoMonitorada", "Regiao")
                        .WithMany("Observacoes")
                        .HasForeignKey("IdRegiao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_OBS_REGIAO");

                    b.Navigation("Regiao");
                });

            modelBuilder.Entity("Amanaje_API.Models.Processamento", b =>
                {
                    b.HasOne("Amanaje_API.Models.RegiaoMonitorada", "Regiao")
                        .WithMany("Processamentos")
                        .HasForeignKey("IdRegiao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_PROCESS_REGIAO");

                    b.HasOne("Amanaje_API.Models.Externals.UsuarioExternal", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_PROCESS_USU");

                    b.Navigation("Regiao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Amanaje_API.Models.RegiaoMonitorada", b =>
                {
                    b.HasOne("Amanaje_API.Models.Externals.ClienteExternal", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_REGIAO_CLI");

                    b.HasOne("Amanaje_API.Models.Externals.UsuarioExternal", "UsuarioDeletor")
                        .WithMany()
                        .HasForeignKey("IdDelPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_REGIAO_DEL_POR");

                    b.Navigation("Cliente");

                    b.Navigation("UsuarioDeletor");
                });

            modelBuilder.Entity("Amanaje_API.Models.RegiaoMonitorada", b =>
                {
                    b.Navigation("Observacoes");

                    b.Navigation("Processamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
